### ISSUE TITLE
タスクランナーがほしい

### ISSUE THREAD

**Issue by ynm3n** [ynm3n/nemmy-backend-sandbox#3]

**Comment by ynm3n** [comment]
taskで`docker compose up`をする前に、ソースコードやDockerfileが変更されてたら再ビルドするような設定ができたら便利かも？

**Comment by ynm3n** [comment]
```yaml
  hello:
    cmds:
      - echo hello
    sources:
      - cmd/**/*
      - internal/**/*
      - Dockerfile
      - .env
```

こんな感じで書くとsourcesで指定したファイルの変更時のみ特定のタスクを実行できそう
https://taskfile.dev/usage/#by-fingerprinting-locally-generated-files-and-their-sources
